name: educational_portal
description: An offline/online app for Class 11 & 12 Computer Science students (User + Admin).
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # File & PDFs
  file_picker: ^8.0.5
  flutter_pdfview: ^1.3.2

  # UI Widgets
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Links, emails, external launch
  url_launcher: ^6.3.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/motivational_quotes.json
    - assets/pdfs/class11/
    - assets/pdfs/class12/
    - assets/pdfs/dpp/